"""Goldilocks field + NTT reference (CPU).

The Goldilocks prime is

    p = 2^64 - 2^32 + 1 = 0xFFFF_FFFF_0000_0001

with multiplicative group order ``p - 1 = 2^32 * (2^32 - 1)``. The
sub-2-power-of-order subgroup is generated by ``g = 7^((p-1) / 2^32)
mod p = 1753635133440165772``; for an NTT of length ``N = 2^k`` we
take ``omega_N = g_root_2pow32 ^ (2^(32 - k))``.

All field elements are stored as Python ``int`` (canonical form in
``[0, p)``); the host translates to ``np.uint64`` only at the buffer
boundary. Reductions use Python's arbitrary-precision integers, so the
reference is unambiguously bit-exact -- no risk of intermediate
overflow or rounding.

NTT reference outputs are cached to ``~/.cache/metal-zk/ntt/`` keyed
by ``(N, input_seed)``. For N <= 2^18 the compute is essentially free
(seconds); N = 2^20 takes a couple of minutes the first time and is
served from disk thereafter. Cache files are bit-exact uint64 binaries.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import numpy as np


P: int = (1 << 64) - (1 << 32) + 1            # Goldilocks prime
ORDER_2_ADICITY: int = 32                     # p - 1 is divisible by 2^32
# Primitive 2^32-th root of unity in Goldilocks (Plonky2 / Risc0 convention).
G_ROOT_2POW32: int = 1753635133440165772


def root_of_unity(log_n: int) -> int:
    """Primitive ``2^log_n``-th root of unity in Goldilocks.

    For ``log_n in [0, 32]``, returns ``G_ROOT_2POW32 ^ (2^(32 - log_n))``.
    Used as the forward-NTT twiddle base.
    """
    if log_n < 0 or log_n > ORDER_2_ADICITY:
        raise ValueError(
            f"log_n={log_n} out of range; Goldilocks supports up to 2^32"
        )
    exponent = 1 << (ORDER_2_ADICITY - log_n)
    return pow(G_ROOT_2POW32, exponent, P)


def random_field_elements(n: int, seed: int) -> np.ndarray:
    """``n`` field elements in canonical form ``[0, p)``, as ``uint64``.

    Uses numpy's PCG64 RNG; rejection-samples to remove the slight bias
    from the open ``[0, 2^64)`` range relative to ``[0, p)``. The
    rejection rate is ``(2^64 - p) / 2^64 ~ 2^-32`` so for typical N
    we discard a handful of draws.
    """
    rng = np.random.default_rng(seed)
    out = np.empty(n, dtype=np.uint64)
    filled = 0
    while filled < n:
        chunk = max(1, (n - filled) * 2)
        raw = rng.integers(0, 1 << 64, size=chunk, dtype=np.uint64,
                           endpoint=False)
        # raw < p -> accept. Python int comparison since uint64 can hold p.
        accepted = raw[raw < np.uint64(P)]
        take = min(len(accepted), n - filled)
        out[filled:filled + take] = accepted[:take]
        filled += take
    return out


# ----------------------------------------------------------------------
# Forward NTT (reference)
# ----------------------------------------------------------------------

def _bit_reverse_indices(n: int) -> np.ndarray:
    """Bit-reversal permutation indices for length n = 2^k."""
    log_n = (n - 1).bit_length()
    assert 1 << log_n == n, f"n={n} is not a power of two"
    idx = np.arange(n, dtype=np.uint32)
    rev = np.zeros_like(idx)
    for b in range(log_n):
        rev |= ((idx >> b) & 1) << (log_n - 1 - b)
    return rev.astype(np.int64)


def ntt_forward_reference(x: np.ndarray) -> np.ndarray:
    """Forward Goldilocks NTT, length n = 2^k.

    Convention: ``Y[k] = sum_n X[n] * omega^(k * n)`` where omega is the
    primitive n-th root of unity (matching ``np.fft.fft`` with negative
    exponent replaced by positive; the NTT analog is sign-agnostic since
    the field has no notion of complex conjugate).

    Uses iterative Cooley-Tukey with a bit-reversed input order. All
    arithmetic is done with Python ``int`` to avoid overflow.
    """
    x = np.asarray(x, dtype=np.uint64)
    n = int(x.shape[0])
    if n & (n - 1) != 0:
        raise ValueError(f"length {n} must be a power of two")
    log_n = (n - 1).bit_length()

    # Move to Python ints in canonical form.
    a = [int(v) % P for v in x.tolist()]
    rev = _bit_reverse_indices(n)
    a = [a[int(rev[i])] for i in range(n)]

    # Iterative butterfly: stage s = 1..log_n, m = 2^s, half = m/2.
    for s in range(1, log_n + 1):
        m = 1 << s
        half = m >> 1
        w_m = root_of_unity(s)             # primitive m-th root
        for k in range(0, n, m):
            w = 1
            for j in range(half):
                t = (a[k + j + half] * w) % P
                u = a[k + j]
                a[k + j]        = (u + t) % P
                a[k + j + half] = (u - t) % P
                w = (w * w_m) % P

    return np.array(a, dtype=np.uint64)


# ----------------------------------------------------------------------
# Cache
# ----------------------------------------------------------------------

_CACHE_VERSION = "v1"


def _cache_dir() -> Path:
    root = Path(os.environ.get("METAL_ZK_CACHE",
                               "~/.cache/metal-zk")).expanduser()
    d = root / "ntt"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _cache_key(n: int, x: np.ndarray) -> str:
    h = hashlib.sha256()
    h.update(_CACHE_VERSION.encode())
    h.update(np.uint64(n).tobytes())
    h.update(np.ascontiguousarray(x, dtype=np.uint64).tobytes())
    return h.hexdigest()[:16]


def ntt_forward_cached(x: np.ndarray) -> np.ndarray:
    """``ntt_forward_reference`` with disk-backed caching.

    Cache key is sha256(N, input bytes). Hits are O(read); misses
    fall through to the pure-Python reference (slow for N = 2^20, but
    one-shot per input).
    """
    n = int(x.shape[0])
    key = _cache_key(n, x)
    path = _cache_dir() / f"N{n}_{key}.u64"
    if path.exists():
        out = np.fromfile(path, dtype=np.uint64)
        if out.shape[0] == n:
            return out
        # Length mismatch (corrupted cache); recompute and overwrite.
    out = ntt_forward_reference(x)
    tmp = path.with_suffix(path.suffix + ".tmp")
    out.tofile(tmp)
    os.replace(tmp, path)
    return out


__all__ = [
    "P",
    "ORDER_2_ADICITY",
    "G_ROOT_2POW32",
    "root_of_unity",
    "random_field_elements",
    "ntt_forward_reference",
    "ntt_forward_cached",
]
